apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: collab-svc-workload
  namespace: default
spec:
  container:
    env:
    - key: DOCLET_COLLAB_ADDR
      value: :8090
    image: host.k3d.internal:10082/doclet-collab-svc-image:v1-8c41917b
  dependencies:
    resources:
    - envBindings:
        url: DOCLET_NATS_URL
      ref: doclet-nats
  endpoints:
    http:
      port: 8090
      type: HTTP
  owner:
    componentName: collab-svc
    projectName: doclet
