apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: document-svc-workload
  namespace: default
spec:
  container:
    env:
    - key: DOCLET_DOCUMENT_ADDR
      value: :8080
    image: host.k3d.internal:10082/doclet-document-svc-image:v1-8c41917b
  dependencies:
    resources:
    - envBindings:
        database: DB_NAME
        host: DB_HOST
        password: DB_PASSWORD
        port: DB_PORT
        username: DB_USER
      ref: doclet-postgres
    - envBindings:
        url: DOCLET_NATS_URL
      ref: doclet-nats
  endpoints:
    http:
      port: 8080
      type: HTTP
      visibility:
      - external
  owner:
    componentName: document-svc
    projectName: doclet
